### ISSUE TITLE
Quick and Good start👏 

### ISSUE THREAD

**Issue by elilovna** [Lucha2040/hyf-homework#1]
You did a great job👏
I don't have a lot of comments about your work. I like that you created a menu for your website. You already have experience with links. You have a great understanding of structuring your code, you added `nav`, `section`, `article`, `footer`. It is really nice that you know how to add icons!!!
It is ok to use`<br>` tag, but you can try to wrap it in `<span>` and add a margin. 

Well done 🥇😃

**Comment by Lucha2040** [comment]
Elinovna Thanks for this devolution!!! (I forgot to close the case, my bad). 
But I followed your advice and forgot that <br> exist jeje. 
Have a lovely week!
