### ISSUE TITLE
math inside array index

### ISSUE THREAD

**Issue by aleks-hyf** [Lucha2040/hyf-homework#10]
https://github.com/Lucha2040/hyf-homework/blob/6978e7db5109b58bb9581871ea21eddd938a1be5/javascript/javascript2/week1/homeworkjs2w1.js#L54

Not recommended. Consider extracting const half = a.length/2, as you are using it in several places.

**Comment by Lucha2040** [comment]
Perfect. 
Implemented in line 20 in PR a83843f7f3c001c02102e24e194d9f024b010348
  `const result = a.length / 2;`

Thanks!
