### ISSUE TITLE
else is not necessary

### ISSUE THREAD

**Issue by aleks-hyf** [Lucha2040/hyf-homework#11]
https://github.com/Lucha2040/hyf-homework/blob/6978e7db5109b58bb9581871ea21eddd938a1be5/javascript/javascript2/week1/homeworkjs2w1.js#L55

Since you have an early exit with return.

**Comment by Lucha2040** [comment]
I had eliminated the else statement in the PR 3685c097eb8112f196a5b22aba52e070954b7419. 
Thanks!
