### ISSUE TITLE
Extract into function

### ISSUE THREAD

**Issue by aleks-hyf** [Lucha2040/hyf-homework#12]
https://github.com/Lucha2040/hyf-homework/blob/6978e7db5109b58bb9581871ea21eddd938a1be5/javascript/javascript2/week1/homeworkjs2w1.js#L95

Math.floor(Math.random()*10 used several times. Better yet, use the length of the array.

**Comment by Lucha2040** [comment]
Implemented feedback in PR 2f1e0462c35c5464dadbe141b0a847c608615c29. Thanks! 

```
function randomIndex () {
  return  Math.floor(Math.random()*10);
}
```
