### ISSUE TITLE
nice use of Regex

### ISSUE THREAD

**Issue by aleksd-dfds** [Lucha2040/hyf-homework#13]
https://github.com/Lucha2040/hyf-homework/blob/5ebab50a26ad092cc140519293363364e50eeea6/javascript/javascript2/week2/hwjs2w2movies.js#L44643

However, if you're using regex, you might as well put in all of the strings into one Regex instead of having 3 separate ones.

**Comment by Lucha2040** [comment]
Yes! But I was a bit confuse about how to write it (and I play safe, just in case).  I might work on this during summer to improve the code. Thanks!

**Comment by Lucha2040** [comment]
Exactly as you pointed out, the code looks cleaner this way. 
const specialWords = new RegExp("surfer|benjamin|alien", "gi");
Thanks!
PR: 2e768bd3d74061989fb91924f26984040f5f57a5
