### ISSUE TITLE
What is 657?

### ISSUE THREAD

**Issue by aleksd-dfds** [Lucha2040/hyf-homework#14]
https://github.com/Lucha2040/hyf-homework/blob/5ebab50a26ad092cc140519293363364e50eeea6/javascript/javascript2/week2/hwjs2w2movies.js#L44621

Shouldn't you be using moviesWithTag that you just created?

**Comment by Lucha2040** [comment]
Yes I know! but that's why I comment that the original array changed while the moviesWithTags became a bag of undefined...

**Comment by Lucha2040** [comment]
Finally managed to solve this. Thanks! 

const moviesWithTag = movies.map((movie) => {
  if (movie.rating >= 7) {
    movie.tag = "Good";
  } else if (movie.rating >= 4) {
    movie.tag = "Average";
  } else {
    movie.tag = "Bad";
  }
  return movie;
});
  
PR: 2e768bd3d74061989fb91924f26984040f5f57a5
