### ISSUE TITLE
Notes about getting stuck don't belong in the code :)

### ISSUE THREAD

**Issue by aleksd-dfds** [Lucha2040/hyf-homework#15]
https://github.com/Lucha2040/hyf-homework/blob/5ebab50a26ad092cc140519293363364e50eeea6/javascript/javascript2/week2/hwjs2w2movies.js#L44654

This comment won't pass you an interview. It is important you understand how to do it, as it is similar to some test questions you might get on a coding test. Ask around, few others in the class managed.

**Comment by Lucha2040** [comment]
I don't know what I was thinking.. sorry. 
Thanks for teaching me to be more professional.
