### ISSUE TITLE
inline the functions

### ISSUE THREAD

**Issue by aleksd-dfds** [Lucha2040/hyf-homework#17]
https://github.com/Lucha2040/hyf-homework/blob/5ebab50a26ad092cc140519293363364e50eeea6/javascript/javascript2/week2/hwjs2w2movies.js#L44634

It is a better practice to inline the functions, instead of declaring them above. Makes the code clearer. 
Also i prefer arr.year to arr["year"] as it's less typing and easier to read.

**Comment by Lucha2040** [comment]
This was exchange for this in the PR 2e768bd3d74061989fb91924f26984040f5f57a5: 
```
const higherThan6 = movies
  .filter((movie) => movie.rating > 6)
  .map((movie) => movie.rating);
console.log(higherThan6);
```
