### ISSUE TITLE
inline and chain

### ISSUE THREAD

**Issue by aleksd-dfds** [Lucha2040/hyf-homework#18]
https://github.com/Lucha2040/hyf-homework/blob/5ebab50a26ad092cc140519293363364e50eeea6/javascript/javascript2/week2/hwjs2w2.js#L10

Better to inline the functions and chain => the whole thing becomes one line. 

Good effort on the homework overall, just make sure you incorporate my comments and know how to do the difficult parts.

**Comment by Lucha2040** [comment]
Thanks, is so much nicer. 
PR: 2e768bd3d74061989fb91924f26984040f5f57a5
`
let doubleOdds = numbers.filter((num) => num % 2 !== 0).map((num) => num * 2)`
