### ISSUE TITLE
Homework Feedback - HTML/CSS - week 2

### ISSUE THREAD

**Issue by susaneme** [Lucha2040/hyf-homework#2]
Hi Lucha :)

Your site look very much the same as the exercise requirement! 👏  That is a huge milestone, already ! Congratulations for all the hard work you put not only in the homework, but also in the class and with all exercises. You always try to understand the ‘why’ behind of each element ... In a sense of ‘why’ does it exist? ‘why’ do I need to use it? And that is very very important to understand the reason you are development that, so you can better choose the strategy when converting a design into code. Super congrats 😸 🌹

 - Your html is very semantic, you used all the right tags for the right blocks, <header> for the header of your website, <nav> for your navigation...Nice nice! 🆒 
- I would say is not only semantic, is clean, organized and well indented, by just a quick look I could understand how your page functions 👍 
- I am wondering that you have might did some stretches before get your hands into coding... I am guessing that because of the way you named your classes `box-3` or similars...  Remember to name your classes as meaningful as possible, for this example you could hav used something like: `gallery-section` or just `gallery`.
- Regarding your HTML that is the only observation I would do! Because everything else looks awesome! It is also perceptual your organization on not use overusing classes. Super super!
- Your CSS has the same compliments as your html: organized, clean and concise. 😍 
- I encourage you to take a second look at your `Navigation`  and ‘Gallery’ section , as I scaled up and down the `about` nav is not vertical and the `gallery` for example is not going to the next row. I am reviewing on my , so I am not sure that could be something on my device’s capabilities. 

A HUGE congrats for the way you are handling your studies and also your homework! ❤️

**Comment by Lucha2040** [comment]
Susane! 
Please laugh with me, I just discovered now that I need to close the cases (sometimes I am not the smartest haha). 
I will close it soon but first i want to do the modifications you pointed out (but i want to read a bit more for Javascript before, I don't want to be behind). 
I am also asking myself "why" you are not around anymore, it was great to have you in class! But I don't complain about the new teachers, they are super cool too. 
Thanks for such a complete and encouraging devolution, I felt a bit more confident after reading this XD

**Comment by Lucha2040** [comment]
> Classes and Id's modified to be specific in each case. 
> Navigation Bar linked to sections. 
> Navigation and Gallery responsiveness improved. 

Thank you so much for your devolution!
