### ISSUE TITLE
Much easier to write this with filters

### ISSUE THREAD

**Issue by aleks-hyf** [Lucha2040/hyf-homework#24]
Try to get used to the "JS way". In this case a filter is more expressive and shorter than the old fashioned for-loop

**Comment by Lucha2040** [comment]
Aleks, 
It was a rough started but now I am getting that JS is not just a language but a way of thinking. 
Thanks for this feedback. 

The code associated to this issue was developed further in: 
Branch https://github.com/Lucha2040/hyf-homework/pull/48
javascript/javascript3/week3
