### ISSUE TITLE
Homework Feedback - HTML/CSS - week 3

### ISSUE THREAD

**Issue by senner008** [Lucha2040/hyf-homework#3]
Hi :)
Great homework.
You have great understanding of html! Try to challenge yourself to add more validation. Use placeholders and more descriptive names. Inform user about requirements.
Please read the comments and update. Ask if you have questions
Good work!

**Comment by Lucha2040** [comment]
Hi Niels, thanks for the devolution. I just discovered that I have this section as part of the review in the homework, so this week I am gonna be working on solving all and closing the cases. See you soon!
