### ISSUE TITLE
Homework Feedback JS1- Week3

### ISSUE THREAD

**Issue by Swapna-Sahu** [Lucha2040/hyf-homework#6]
Good job 👍 . Almost everything looks good. I can see fast learning here. 

Item array removal Task -

Task was removing random name using random method.
Here, you are choosing the position and removing it.
For removing random name from the array either you use for loop inside If statement or you can just check the index of the element which is matching then slice it.

Enjoy coding and feel free to ask in channel and also PM to me .

**Comment by Swapna-Sahu** [comment]
// 3)  Get all the notes together  - yes it is so simple but we have to create a function to just console log the notes. because when user want to see the notes he will call function instead of writing console.log

**Comment by Swapna-Sahu** [comment]
let lifeSpan = 80 * 525600 ;
for (let i = 0; i < seriesDurations.length; i++) {
    
    let daysInMins = seriesDurations[i].days;
    daysInMins = daysInMins * 1440; 
    let hoursInMins = seriesDurations[i].hours;
    hoursInMins = hoursInMins * 60;
    let mins = seriesDurations[i].minutes;
       let totalTimeInMins = daysInMins + hoursInMins + mins;
}

**Comment by Lucha2040** [comment]
Swapna, the feedback was implemented in PR 51694cd0cfc20a7c35b4b57a5115394c474c9f7f. 
Thanks!
