### ISSUE TITLE
good

### ISSUE THREAD

**Issue by aleks-hyf** [Lucha2040/hyf-homework#8]
https://github.com/Lucha2040/hyf-homework/blob/6978e7db5109b58bb9581871ea21eddd938a1be5/javascript/javascript2/week1/homeworkjs2w1.js#L18

Nice work, obviously this gets easier with maps and filters.

**Comment by Lucha2040** [comment]
Hi Aleks! 
I finally implemented this feedback in the PR d0667a75679f1b9c143835fc5bd8ec1e48d79594 
Maybe it's not perfect but it allows me to use it with any array and to find all the elements with the minimun length. Thanks! 
`
function getShorty(arr) {  
  const getLength = arr.map((el) => {return el.length})
  const getShortest = Math.min.apply(null, getLength)
  const shorty = arr.filter((el) => {return el.length === getShortest})
  return shorty
}
 `
